### ISSUE TITLE
Basic api's to be implemented

### ISSUE THREAD

**Issue by ankitchiplunkar** [analyseether/ether-api#4]
**Is your feature request related to a problem? Please describe.**
We need to implement the basic API's similar to json-rrpc in the library.

**Describe the solution you'd like**
API's to be implemented -> their corresponding json-rpc
`current_blockNumber` -> eth_blockNumber
`getTransactionCount` ->  {eth_getBlockTransactionCountByHash, eth_getBlockTransactionCountByNumber}
`getUncleCount` -> {eth_getUncleCountByBlockHash, eth_getUncleCountByBlockNumber}
`getBlock` -> {eth_getBlockByHash, eth_getBlockByNumber}
`getTransaction` -> {eth_getTransactionByHash, eth_getTransactionByBlockHashAndIndex
, eth_getTransactionByBlockNumberAndIndex}
`getReceipt` -> {eth_getTransactionReceipt}
`getUncle` -> {eth_getUncleByBlockHashAndIndex, eth_getUncleByUncleHash, eth_getUncleByBlockNumberAndIndex}

Similar to  https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-methods

**Comment by SaranshVatsa** [comment]
Alright, I'll try to make the change in names according to what I've understood of this. Kindly check after my next commit if I've done it correctly.

**Comment by SaranshVatsa** [comment]
So I have corrected the names of the existing ones.
So for getting transaction by Block Hash and Transaction Index, Block Hash is a column in the blocks table and Transaction Index is in transactions table. Transactions table has block number as a column. SO do I first find block number using the block hash in the blocks table, and then use that block number and the transaction index to find the transaction?

**Comment by ankitchiplunkar** [comment]
It would be better if we use the SQLALchemy ORM instead of writing the SQL queries in the python code.
This would also easily allow us to leverage us the relationship between `blocks` table and `transactions` table.

**Comment by SaranshVatsa** [comment]
Alright, I shall do that. From the way I look at it, since the API is querying the same database that the ether-sql library creates, I will just create object relations for every table that we are querying as and when required and use the SQLAlchemy ORM querying tools to query them. I too believe that this will be the best approach. I will look into the SQLAlchemy library and make the required changes accordingly.

**Comment by SaranshVatsa** [comment]
current_blockNumber -> eth_blockNumber
getTransactionCount -> {eth_getBlockTransactionCountByHash, eth_getBlockTransactionCountByNumber}
getUncleCount -> {eth_getUncleCountByBlockHash, eth_getUncleCountByBlockNumber}
getBlock -> {eth_getBlockByHash, eth_getBlockByNumber}
getTransaction -> {eth_getTransactionByHash, eth_getTransactionByBlockHashAndIndex
, eth_getTransactionByBlockNumberAndIndex}
getReceipt -> {eth_getTransactionReceipt}
getUncle -> { eth_getUncleByUncleHash}


All these are done :)

eth_getUncleByBlockHashAndIndex and eth_getUncleByBlockNumberAndIndex are left.
I need clarifications regarding these. The Uncles' table does not have any "Index" field (like the transactions table had the 'transaction_index'), but uncle's table doesn't have any. 
I can use block hash to get the block number, block number field is there in uncles' table so that's alright, but what should I take as the Index column in this case? @ankitchiplunkar
